{
 "title": "EDS Status Monitor",
 "description": "이벤트 분배서버 모니터링",
 "tags": [ "nodejs" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "서버별 이벤트 발생 현황",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(increase(eds_snapshot_total[1m])) by (serverId)",
     "legendFormat": "{{serverId}}"
    }
   ]
  },
  {
   "title": "이벤트 발생 현황",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(eds_snapshot_total[1m]))",
     "legendFormat": "스넵샷"
    },
    {
     "expr": "sum (increase(eds_event_total[1m]))",
     "legendFormat": "오브젝트"
    }
   ]
  },
  {
   "title": "이벤트 TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(eds_snapshot_total[1m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "분배 TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(eds_dispatch_total[1m]))",
     "legendFormat": "분배 TPS"
    }
   ]
  },
  {
   "title": "분배 현황",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(eds_dispatch_total[1m]))",
     "legendFormat": "분배 전송"
    },
    {
     "expr": "sum(increase(eds_dispatch_error[1m]))",
     "legendFormat": "분배 전송 실패"
    }
   ]
  },
  {
   "title": "분배 성공율",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (increase(eds_dispatch_success[1m])) / sum(increase(eds_dispatch_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "사람 이벤트",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(targetEvent) (increase(eds_event_total{targetObject='PERSON'}[1m]))",
     "legendFormat": "{{targetEvent}}"
    }
   ]
  },
  {
   "title": "차량 이벤트",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(targetEvent) (increase(eds_event_total{targetObject='CAR'}[1m]))",
     "legendFormat": "{{targetEvent}}"
    }
   ]
  },
  {
   "title": "오브젝트 분포율",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(targetObject) (rate(eds_event_total{targetObject!=''}[1m]))",
     "legendFormat": "{{targetObject}}"
    }
   ]
  },
  {
   "title": "클라이언트 별 현황",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(clientId) (increase(eds_dispatch_total[1m]))",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "분배 처리 속도",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "( sum(irate(eds_dispatch_send_duration_bucket{le=\"5\"}[1m])) /  sum(irate(eds_dispatch_send_duration_count[1m])) )  * 100",
     "legendFormat": "Duration<5ms (%)"
    },
    {
     "expr": "( sum(irate(eds_dispatch_send_duration_bucket{le=\"100\"}[1m])) /  sum(irate(eds_dispatch_send_duration_count[1m])) )  * 100",
     "legendFormat": "Duration<100ms (%)"
    },
    {
     "expr": "( sum(irate(eds_dispatch_send_duration_bucket{le=\"1000\"}[1m])) /  sum(irate(eds_dispatch_send_duration_count[1m])) )  * 100",
     "legendFormat": "Duration<1000ms (%)"
    },
    {
     "expr": "( sum(irate(eds_dispatch_send_duration_bucket{le=\"+Inf\"}[1m])) /  sum(irate(eds_dispatch_send_duration_count[1m])) )  * 100",
     "legendFormat": "Duration>1000ms (%)"
    }
   ]
  },
  {
   "title": "차량 분포율",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(objectType) (rate(eds_event_total{objectType!=''}[1m]))",
     "legendFormat": "{{objectType}}"
    }
   ]
  },
  {
   "title": "CPU 사용 현황",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "메모리 사용 현황",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Process Memory - {{instance}}" },
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Heap Total - {{instance}}" },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "이벤트 루프 현황",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}