# networks:
#   dms_default:
#     name: dms_default
services:
  nginx:
    # image: nginx:1.21.6
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8090:8090"
    environment:
      - NGINX_PORT=8090
    volumes:
      - ./dist/:/usr/share/nginx/html/