volumes:
  v-portainer:
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: --admin-password '$$2y$$05$$VsTwtnZtA7tagg7ReNmk4eOgeBULb05kbTrzRMtr2jL4L9mv5IwOS'
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - v-portainer:/data
    working_dir: /
    restart: always
