# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: db
    # image: postgres
    image: realhubvms/postgres
    # image: postgres-euckr
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=nice2122!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - v-postgres:/var/lib/postgresql/data \
  testdb:
    container_name: testdb
    # image: postgres
    image: realhubvms/postgres
    # image: postgres-euckr
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=nice2122!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - v-postgres2:/var/lib/postgresql/data \
volumes:
  v-postgres:
  v-postgres2: